# 配置项目名
server:
  servlet:
    context-path: /
  port: 8080

spring:
  # 模板配置
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path: classpath:/templates
  mvc:
    view:
      #页面默认前缀目录
      prefix: /WEB-INF/jsp/
      #页面默认后缀目录
      suffix: .jsp
    #Spring Boot的默认静态资源访问的路径
    static-path-pattern: /static/**
#  datasource:
#    #1.JDBC
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/t222?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 123
#    druid:
#      #2.连接池配置
#      #初始化连接池的连接数量 大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      #配置获取连接等待超时的时间
#      max-wait: 60000
#      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 30000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filter:
#        stat:
#          merge-sql: true
#          slow-sql-millis: 5000
#      #3.基础监控配置
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        #设置不统计哪些URL
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-enable: true
#        session-stat-max-count: 100
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: true
#        #设置监控页面的登录名和密码
#        login-username: admin
#        login-password: admin
#        allow: 127.0.0.1
        #deny: 192.168.1.100
#  redis:
#    database: 0
#    host: 192.168.126.128
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 3
#        max-wait: -1
#        min-idle: 0
#    timeout: 1000
# mybatis配置
#mybatis:
#  #SQL映射文件配置
#  mapper-locations: classpath:mapper/*.xml
#  #配置别名
#  type-aliases-package: com.homolo.module.model
#  #驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true

#pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#显示日志
#logging:
#  level:
#    com.homole.module.mapper: debug



